version: "3.8"

services:
  postgres:
    image: postgres:16.4-alpine
    container_name: amcred-2-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - .tmp/postgresql:/var/lib/postgresql/data
    command: ["postgres","-c","listen_addresses=*"]